services:
  ti4-api:
    build:
      context: ./ti4-assistant-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    
  ti4-web:
    build:
      context: ./UI/ti4-round-assistant-web-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./UI/ti4-round-assistant-web-app:/app
      - /app/node_modules
    depends_on:
      - ti4-api